/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patitas_vet;

import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author laboratorioesan
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
        txtBusqueda.setVisible(true);
        spinnerBusqueda.setVisible(false);
        btnEditar.setEnabled(false);
        fillCmb();
        fillCmbColums();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBusqueda = new javax.swing.JTable();
        cmbTabla = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbColums = new javax.swing.JComboBox<>();
        panelBusqueda = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        spinnerBusqueda = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Busqueda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableBusquedaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tableBusqueda);

        cmbTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTablaActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por: ");

        cmbColums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColums.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbColumsItemStateChanged(evt);
            }
        });
        cmbColums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbColumsMouseClicked(evt);
            }
        });
        cmbColums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColumsActionPerformed(evt);
            }
        });

        txtBusqueda.setText(" ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbColums, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbColums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnEditar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        fillTabla();
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTablaActionPerformed
        fillCmbColums();   
        String tabla = (String) cmbTabla.getSelectedItem();
        System.out.println(tabla);
        btnEditar.setEnabled(false);
        switch(tabla){
            case "Cliente":
            case "Paciente":
            case "Estetica":
            case "Diagnostico":
                btnEditar.setEnabled(true);
            break;
                
        }
        fillTabla();
        txtBusqueda.setText("");
    }//GEN-LAST:event_cmbTablaActionPerformed

    private void cmbColumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColumsActionPerformed
        
    }//GEN-LAST:event_cmbColumsActionPerformed

    private void cmbColumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbColumsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColumsMouseClicked

    private void cmbColumsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbColumsItemStateChanged
        String tipo = getColumType();
        System.out.println(tipo);
        txtBusqueda.setVisible(false);
        spinnerBusqueda.setVisible(false);
        switch(tipo){
            case "varchar":
            case "nvarchar":
            case "char":
            case "date":
                txtBusqueda.setVisible(true);
                txtBusqueda.setText("");
                break;
            case "bit":
                spinnerBusqueda.setVisible(true);
                SpinnerNumberModel b = new SpinnerNumberModel(0, 0, 1, 1);
                spinnerBusqueda.setModel(b);
                break;
            case "int":
                spinnerBusqueda.setVisible(true);
                SpinnerNumberModel a = new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1);
                spinnerBusqueda.setModel(a);
                break;
            case "None":
                txtBusqueda.setVisible(true);
                break;
        }
    }//GEN-LAST:event_cmbColumsItemStateChanged

    private void tableBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableBusquedaFocusGained
        
    }//GEN-LAST:event_tableBusquedaFocusGained
    public String[] getTableData(){
        int index = tableBusqueda.getSelectedRow();
        if (index == -1){
            JOptionPane.showMessageDialog(rootPane, "No hay fila seleccionada");
            
        }else{
            int rowLen = tableBusqueda.getColumnCount();
            String[] a = new String[rowLen];
            for (int i = 0; i < rowLen; i++){
                Object dato = tableBusqueda.getValueAt(index, i);
                a[i] = (dato != null)? dato.toString() : "";
            }
            return a;
        }
        return null;
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String[] tableData = getTableData();
        String tabla = cmbTabla.getSelectedItem().toString();
        switch(tabla){
            case "Cliente":
                registro_clientes registroClientes = new registro_clientes(tableData);
                registroClientes.setVisible(true);
                this.dispose();
                break;
            case "Paciente":
                registros_pacientes registroPacientes = new registros_pacientes(tableData);
                registroPacientes.setVisible(true);
                this.dispose();
                break;
            case "Estetica":
                registro registroA = new registro(tableData, null);
                registroA.setVisible(true);
                this.dispose();
                break;
            case "Diagnostico":
                registro registroB = new registro(null, tableData);
                registroB.setVisible(true);
                this.dispose();
        }
        if (tableData != null) {
        for (String dato : tableData) {
            System.out.print(dato + "!!");
        }
        System.out.println();
}
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Busqueda().setVisible(true);
                
            }
        });
    }
    
    public String getColumType(){
        try {
            String tabla = cmbTabla.getSelectedItem().toString();
            String colum = cmbColums.getSelectedItem().toString();
            System.out.println(tabla);
            System.out.println(colum);
            ConnectToServer bd = new ConnectToServer();
            String query = "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '"
                    + tabla
                    + "' and COLUMN_NAME = '"
                    + colum
                    + "'";
            System.out.println(query);
            bd.conectaSql();
            ResultSet rs = bd.querySql(query);
            ResultSetMetaData metadata = rs.getMetaData();
            int colums = metadata.getColumnCount();
            while (rs.next()) {
                Object fila = new Object();
                for (int i = 0; i < colums; i++) {
                    fila = rs.getObject(colums);
                }
                return fila.toString();
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "None";
    }
    public void fillCmbColums(){
        try {
            String tabla = cmbTabla.getSelectedItem().toString();
            ConnectToServer bd = new ConnectToServer();
            DefaultComboBoxModel cmb = new DefaultComboBoxModel();
            String query = "select B.name from sysobjects A, syscolumns B where A.id = B.id and A.name = '" + tabla + "' order by B.colid";
            bd.conectaSql();
            ResultSet rs = bd.querySql(query);
            ResultSetMetaData metadata = rs.getMetaData();
            int colum = metadata.getColumnCount();
            Object nada = new Object();
            nada = "";
            cmb.addElement(nada);
            while (rs.next()) {
                Object fila = new Object();
                for (int i = 0; i < colum; i++) {
                    fila = rs.getObject(colum);
                }
                cmb.addElement(fila);
            }
            cmbColums.setModel(cmb);
            bd.cierraSql();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void fillCmb(){
        try {
            ConnectToServer bd = new ConnectToServer();
            DefaultComboBoxModel cmb = new DefaultComboBoxModel();
            String query = "select Name from sysobjects where xtype='U'";
            bd.conectaSql();
            ResultSet rs = bd.querySql(query);
            ResultSetMetaData metadata = rs.getMetaData();
            int colum = metadata.getColumnCount();
            while (rs.next()) {
                Object fila = new Object();
                for (int i = 0; i < colum; i++) {
                    fila = rs.getObject(colum);
                }
                cmb.addElement(fila);
            }
            cmbTabla.setModel(cmb);
            bd.cierraSql();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fillTabla(){
        String tabla = cmbTabla.getSelectedItem().toString();
        try {
            String q = "select * from " + tabla;
            if(!"".equals(cmbColums.getSelectedItem().toString()) || !"".equals(txtBusqueda.getText().trim())){
                
                String name = cmbColums.getSelectedItem().toString();
                String search;
                if(txtBusqueda.isVisible()){
                    search = txtBusqueda.getText().trim();
                }else{
                    search = spinnerBusqueda.getValue().toString().trim();
                }
                
                if(!"".equals(search.trim())){
                   q = q + " where " + name + " = '" + search +"'"; 
                }
                
                
            }
            ConnectToServer bd = new ConnectToServer();
            bd.conectaSql();
            
            ResultSet rs = bd.querySql(q);
            ResultSetMetaData metadata = rs.getMetaData();
            int colum = metadata.getColumnCount();
            
            DefaultTableModel modelo = new DefaultTableModel(){
              @Override
              public boolean isCellEditable(int row, int column){
                  return false;
              }
            };
            for (int i = 1; i <= colum; i++) {
                modelo.addColumn(metadata.getColumnLabel(i));
            }
            
            //agregar los nombres a las filas
            while (rs.next()) {
                Object[] fila = new Object[colum];
                for (int i = 0; i < colum; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            tableBusqueda.setModel(modelo);
            tableBusqueda.getTableHeader().setReorderingAllowed(false);

            bd.cierraSql();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(ConnectToServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbColums;
    private javax.swing.JComboBox<String> cmbTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JSpinner spinnerBusqueda;
    private javax.swing.JTable tableBusqueda;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
