insert into Concepto values('01', 'Baño');
insert into Concepto values('02', 'Corte de Pelo');
insert into Concepto values('03', 'Recorte de Uñas');
insert into Concepto values('04', 'Limpieza de Orejas');
insert into Concepto values('05', 'Baño Medicado');
insert into Concepto values('06', 'Desparasitacion Ext');
insert into Concepto values('07', 'Limpieza Dental');
insert into Concepto values('08', 'Hidratacion de Piel');
insert into Concepto values('09', 'Aplicacion Perfume');

insert into Tipos_Diagnostico values('0101', 'Otitis Externa');
insert into Tipos_Diagnostico values('0102', 'Dermatitis Atopica');
insert into Tipos_Diagnostico values('0103', 'Parvovirosis Canina');
insert into Tipos_Diagnostico values('0104', 'Moquillo Canino');
insert into Tipos_Diagnostico values('0105', 'Gastroenteritis Canina');
insert into Tipos_Diagnostico values('0106', 'Leishmaniasis');
insert into Tipos_Diagnostico values('0107', 'Infeccion Urinaria');
insert into Tipos_Diagnostico values('0108', 'Artritis Canina');
insert into Tipos_Diagnostico values('0109', 'Parasitos Intestinales Caninos');
insert into Tipos_Diagnostico values('0110', 'Torsion Gastrica');
insert into Tipos_Diagnostico values('0111', 'Cistitis');
insert into Tipos_Diagnostico values('0112', 'Tumor Cutaneo');
insert into Tipos_Diagnostico values('0113', 'Hipotiroidismo');
insert into Tipos_Diagnostico values('0114', 'Conjuntivitis');
insert into Tipos_Diagnostico values('0201', 'FIV Felina');
insert into Tipos_Diagnostico values('0202', 'Leucemia Felina');
insert into Tipos_Diagnostico values('0203', 'Gingivoestomatitis');
insert into Tipos_Diagnostico values('0204', 'Enfermedad Renal Cronica');
insert into Tipos_Diagnostico values('0205', 'Diabetes Mellitus');
insert into Tipos_Diagnostico values('0206', 'Hipertiroidismo');
insert into Tipos_Diagnostico values('0207', 'Parasitos Intestinales Felinos');
insert into Tipos_Diagnostico values('0208', 'Gripe Felina');
insert into Tipos_Diagnostico values('0209', 'Dermatitis');
insert into Tipos_Diagnostico values('0210', 'Absesos');
insert into Tipos_Diagnostico values('0211', 'Bloqueo Urinario');
insert into Tipos_Diagnostico values('0212', 'Conjuntivitis');
insert into Tipos_Diagnostico values('0301', 'Mixomatosis');
insert into Tipos_Diagnostico values('0302', 'VHD');
insert into Tipos_Diagnostico values('0303', 'Pasteurelosis');
insert into Tipos_Diagnostico values('0304', 'Gastroenteritis Conejil');
insert into Tipos_Diagnostico values('0305', 'Estasis Gastrointestinal');
insert into Tipos_Diagnostico values('0306', 'Maloclusion');
insert into Tipos_Diagnostico values('0307', 'Parasitosis');
insert into Tipos_Diagnostico values('0308', 'Pododermatitis');
insert into Tipos_Diagnostico values('0309', 'Urolitasis');
insert into Tipos_Diagnostico values('0401', 'Colicos');
insert into Tipos_Diagnostico values('0402', 'Laminitis');
insert into Tipos_Diagnostico values('0403', 'Artritis Equina');
insert into Tipos_Diagnostico values('0404', 'Enfermedad de Cushing');
insert into Tipos_Diagnostico values('0405', 'Influenza Equina');
insert into Tipos_Diagnostico values('0406', 'Anemia Infecciosa Equina');
insert into Tipos_Diagnostico values('0407', 'Herpesvirus Equino');
insert into Tipos_Diagnostico values('0408', 'Tetanos');
insert into Tipos_Diagnostico values('0409', 'Osteoartritis');
insert into Tipos_Diagnostico values('0410', 'Ulceras Gastricas');

insert into Tipos_Mascota values('0101', 'Mestizo');
insert into Tipos_Mascota values('0102', 'GoldenRetriever');
insert into Tipos_Mascota values('0103', 'Chihuahua');
insert into Tipos_Mascota values('0104', 'Bulldog Frances');
insert into Tipos_Mascota values('0105', 'Poodle');
insert into Tipos_Mascota values('0106', 'Shih Tzu');
insert into Tipos_Mascota values('0107', 'Pastor Aleman');
insert into Tipos_Mascota values('0108', 'Rottweiler');
insert into Tipos_Mascota values('0109', 'Beagle');
insert into Tipos_Mascota values('0110', 'Schnauzer');
insert into Tipos_Mascota values('0111', 'Pomerania');
insert into Tipos_Mascota values('0112', 'Boxer');
insert into Tipos_Mascota values('0113', 'Doberman');
insert into Tipos_Mascota values('0114', 'Cocker Spaniel');
insert into Tipos_Mascota values('0115', 'Pitbull Terrier');
insert into Tipos_Mascota values('0116', 'Husky Siberiano');
insert into Tipos_Mascota values('0117', 'Dachshund');
insert into Tipos_Mascota values('0118', 'Boston Terrier');
insert into Tipos_Mascota values('0119', 'York Terrier');
insert into Tipos_Mascota values('0120', 'LabradorRetriever');
insert into Tipos_Mascota values('0201', 'Mestizo');
insert into Tipos_Mascota values('0202', 'Persa');
insert into Tipos_Mascota values('0203', 'Siames');
insert into Tipos_Mascota values('0204', 'Maine Coon');
insert into Tipos_Mascota values('0205', 'Ragdoll');
insert into Tipos_Mascota values('0206', 'Bengala');
insert into Tipos_Mascota values('0207', 'Sphynx');
insert into Tipos_Mascota values('0208', 'British SH');
insert into Tipos_Mascota values('0209', 'Azul Ruso');
insert into Tipos_Mascota values('0210', 'Scottish Fold');
insert into Tipos_Mascota values('0211', 'Abisino');
insert into Tipos_Mascota values('0212', 'Angora Turco');
insert into Tipos_Mascota values('0213', 'Oriental SH');
insert into Tipos_Mascota values('0214', 'Bosque Noruega');
insert into Tipos_Mascota values('0215', 'Birmano');
insert into Tipos_Mascota values('0216', 'Himalayo');
insert into Tipos_Mascota values('0301', 'Mestizo');
insert into Tipos_Mascota values('0302', 'Holland Lop');
insert into Tipos_Mascota values('0303', 'Mini Rex');
insert into Tipos_Mascota values('0304', 'NetherlandDwarf');
insert into Tipos_Mascota values('0305', 'Lionhead');
insert into Tipos_Mascota values('0306', 'Flemish Giant');
insert into Tipos_Mascota values('0307', 'Californiano');
insert into Tipos_Mascota values('0308', 'English Lop');
insert into Tipos_Mascota values('0309', 'Dutch');
insert into Tipos_Mascota values('0310', 'Angora Ingles');
insert into Tipos_Mascota values('0311', 'Harlequin');
insert into Tipos_Mascota values('0312', 'Satin');
insert into Tipos_Mascota values('0313', 'Havana');
insert into Tipos_Mascota values('0314', 'Chinchilla');
insert into Tipos_Mascota values('0315', 'Rex Estandar');
insert into Tipos_Mascota values('0316', 'Polish');
insert into Tipos_Mascota values('0317', 'New Zealand');
insert into Tipos_Mascota values('0318', 'Mini Lop');
insert into Tipos_Mascota values('0319', 'Jersey Wooly');
insert into Tipos_Mascota values('0320', 'Silver Marten');
insert into Tipos_Mascota values('0321', 'English Spot');
insert into Tipos_Mascota values('0401', 'Mestizo');
insert into Tipos_Mascota values('0402', 'Arabe');
insert into Tipos_Mascota values('0403', 'PuraSangre Ing.');
insert into Tipos_Mascota values('0404', 'Cuarto de Milla');
insert into Tipos_Mascota values('0405', 'Andaluz');
insert into Tipos_Mascota values('0406', 'Appaloosa');
insert into Tipos_Mascota values('0407', 'Hanoveriano');
insert into Tipos_Mascota values('0408', 'Frison');
insert into Tipos_Mascota values('0409', 'Lusitano');
insert into Tipos_Mascota values('0410', 'Percheron');
insert into Tipos_Mascota values('0411', 'Clydesdale');
insert into Tipos_Mascota values('0412', 'Shire');
insert into Tipos_Mascota values('0413', 'Belga');
insert into Tipos_Mascota values('0414', 'Shetland');
insert into Tipos_Mascota values('0415', 'Welsh');
insert into Tipos_Mascota values('0416', 'Connemara');
insert into Tipos_Mascota values('0417', 'Criollo');
insert into Tipos_Mascota values('0418', 'Mustang');

insert into Tipos_Vacuna values('101', 'Polivalente');
insert into Tipos_Vacuna values('102', 'Rabia Canina');
insert into Tipos_Vacuna values('103', 'Desparasitacion');
insert into Tipos_Vacuna values('104', 'Puppy DP');
insert into Tipos_Vacuna values('105', 'Bordetella');
insert into Tipos_Vacuna values('106', 'Giardia');
insert into Tipos_Vacuna values('201', 'Leucemia Felina');
insert into Tipos_Vacuna values('202', 'Rinotraequeitis');
insert into Tipos_Vacuna values('203', 'Calcivirus');
insert into Tipos_Vacuna values('204', 'Rabia Felina');
insert into Tipos_Vacuna values('205', 'FIV Felina');
insert into Tipos_Vacuna values('206', 'FIP');
insert into Tipos_Vacuna values('301', 'Mixomatosis');
insert into Tipos_Vacuna values('302', 'EHV');
insert into Tipos_Vacuna values('303', 'Clamidiosis');
insert into Tipos_Vacuna values('401', 'Influenza E');
insert into Tipos_Vacuna values('402', 'Tetanos');
insert into Tipos_Vacuna values('403', 'EHV');
insert into Tipos_Vacuna values('404', 'Rabia Equina');
insert into Tipos_Vacuna values('405', 'Leptospirosis E');
insert into Tipos_Vacuna values('406', 'EIA');
insert into Tipos_Vacuna values('407', 'Piroplasmosis');
